server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceslcwd_hotelservice
    username: root
    password: root1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085
  
      